micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/cdc1`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}

jpa:
  default:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
